#!/bin/bash

ip="127.0.0.1"
database_prd="aiops_local_prd"
partitions=("'2024-05-15'" "'2024-05-14'" "'2024-05-13'" "'2024-05-12'" "'2024-05-11'" "'2024-05-10'" "'2024-05-09'" "'2024-05-08'" "'2024-05-07'" "'2024-05-06'" "'2024-05-05'" "'2024-05-04'" )


##aiops_collect_100000093_mv_minute3_20240515
for partition in ${partitions[@]}
 do
   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=${partition} and time <date_add(HOUR, 3, toDateTime(${partition}));"
   
   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 3, toDateTime(${partition})) and time <date_add(HOUR, 6, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 6, toDateTime(${partition})) and time <date_add(HOUR, 9, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 9, toDateTime(${partition})) and time <date_add(HOUR, 12, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 12, toDateTime(${partition})) and time <date_add(HOUR, 15, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 15, toDateTime(${partition})) and time <date_add(HOUR, 18, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 18, toDateTime(${partition})) and time <date_add(HOUR, 21, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_100000093_mv_minute3_20240515(product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99) SELECT product,domain,interface,code,time,request_time_sum,request_time_max,request_time_min,request_time_avg,request_time_count,success_sum,success_max,success_min,success_avg,success_count,fail_sum,fail_max,fail_min,fail_avg,fail_count,upstream_response_time_sum,upstream_response_time_max,upstream_response_time_min,upstream_response_time_avg,upstream_response_time_count,count,succrate_sum,succrate_max,succrate_min,succrate_avg,succrate_count,request_time_p50,request_time_p90,request_time_p95,request_time_p99 FROM aiops_local_prd.aiops_collect_100000093_mv_minute3 WHERE time >=date_add(HOUR, 21, toDateTime(${partition})) and time <date_add(HOUR, 24, toDateTime(${partition}));"
   
   echo "${database_prd}.aiops_collect_100000093_mv_minute3_20240515-${partition} data has been successfully restored!"
done
echo "${database_prd}.aiops_collect_100000093_mv_minute3_20240515 data has been successfully restored!"


##aiops_collect_1_mv_minute2_20240515
for partition in ${partitions[@]}
 do
   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=${partition} and time <date_add(HOUR, 3, toDateTime(${partition}));"
   
   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 3, toDateTime(${partition})) and time <date_add(HOUR, 6, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 6, toDateTime(${partition})) and time <date_add(HOUR, 9, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 9, toDateTime(${partition})) and time <date_add(HOUR, 12, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 12, toDateTime(${partition})) and time <date_add(HOUR, 15, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 15, toDateTime(${partition})) and time <date_add(HOUR, 18, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 18, toDateTime(${partition})) and time <date_add(HOUR, 21, toDateTime(${partition}));"

   clickhouse-client --host ${ip} --port 9000 --user default --password Aiopschpro@2022 --query "INSERT INTO aiops_local_prd.aiops_collect_1_mv_minute2_20240515(product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency) SELECT product,service,itf,addn,itfGroup,returnCode,ip,accountErrorCode,sourceId,destinationId,type,greyTag,time,total,success,fail,latency,maxLatency,minLatency,sumLatency FROM aiops_local_prd.aiops_collect_1_mv_minute2 WHERE time >=date_add(HOUR, 21, toDateTime(${partition})) and time <date_add(HOUR, 24, toDateTime(${partition}));"
   
   echo "${database_prd}.aiops_collect_1_mv_minute2_20240515-${partition} data has been successfully restored!"
done
echo "${database_prd}.aiops_collect_1_mv_minute2_20240515 data has been successfully restored!"